[versions]
fabric-api = "0.144.3+26.1"
fabric-loader = "0.18.5"
fabric-loom = "1.15-SNAPSHOT"
minecraft = "26.1"
modrinth-minotaur = "2.+"
modmenu = "18.0.0-alpha.8"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
modmenu = { module = "maven.modrinth:modmenu", version.ref = "modmenu" }

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "fabric-loom" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "modrinth-minotaur" }
